services:
  core-process:
    image: core-process
    build:
      context: .
    container_name: core-process
    env_file: 
      - .env
    networks:
      - core

networks:
  core:
    external: true
