services:
  core-process:
    image: core-process
    build:
      context: .
    container_name: core-process
    entrypoint: ["/bin/bash", "/app/update_env.sh"]
    env_file: 
      - /app/.env
    networks:
      - core
    volumes:
      - ./update_env.sh:/app/update_env.sh
      - ./env_files:/app/.env

networks:
  core:
    external: true
