services:
  core-process:
    image: core-process
    build:
      context: .
    container_name: core-process
    environment:
      - CORE_ADDRESS=http://core:8080
      - CORE_USERNAME=
      - CORE_PASSWORD=
      - PROCESS_REFERENCE=rtmp:hls
      - SYNC_INTERVAL_SECONDS=2
    networks:
      - core

networks:
  core:
    external: true
