services:
  core-process:
    image: core-process
    build:
      context: .
    container_name: core-process
    environment:
      - CORE_ADDRESS=http://172.17.0.2:8080
      - CORE_USERNAME=
      - CORE_PASSWORD=
      - PROCESS_REFERENCE=rtmp:hls
      - SYNC_INTERVAL_SECONDS=2
